version: "3"
services:
  app:
    build:
      context: .
      dockerfile: devops/Dockerfile
    ports:
      - ${SERVER_PORT}:5010
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
